### ISSUE TITLE
Check Meeting-1 Report

### ISSUE THREAD

**Issue by niyaziulke** [bounswe/2021SpringGroup9#13]
Please check the meeting report [here](https://github.com/bounswe/2021SpringGroup9/wiki/Meeting-1-Report-26.03.2021). Any feedback is appreciated.

**Comment by zcanfes** [comment]
Maybe we can add the date to the heading of the meeting notes to prevent complications later.

**Comment by niyaziulke** [comment]
I edited it accordingly, thank you.

**Comment by melihaydogd** [comment]
I think it is pretty good. If there is no more comment,  we can close the issue before the lecture.

**Comment by niyaziulke** [comment]
Thank you. I'll continue with the same format then.
