### ISSUE TITLE
Reorganize File Organization for Easier Merge

### ISSUE THREAD

**Issue by niyaziulke** [bounswe/2021SpringGroup9#140]
Everyone wrote their views and tests to files with the same names. This caused many annoying conflicts. For an easier merge and better file organization:

1. Create 2 folders: "views", "tests". 
2. In each folder, create a file named "__init__.py".
3. Move your models, views, and tests to files :  "view_<your_branchname>.py", "test_<your_branchname>.py"
4. Edit your imports accordingly.

**Comment by zcanfes** [comment]
We have completed the tasks in [Meeting 16](https://github.com/bounswe/2021SpringGroup9/wiki/Meeting-16-Report-04.06.2021) and merged the branches into the main branch. I am closing this issue.
