### ISSUE TITLE
Create Logo for our Project

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#238]
It is time to create a logo for the project 🥳. The logo should be lively, simple and related to the content. The tasks are: 

- [x] Create a logo
- [x] Share it with the group and ask their opinions
- [x] Upload that logo to README.md and wiki 

**Deadline: 01.11.2021**

**Comment by niyaziulke** [comment]
I had already created a basic logo and shared with the group during Meeting 3. The members liked it very much. I will finalize it soon.

**Comment by niyaziulke** [comment]
Since the group members liked it, I'm adding the logo to [README.md](https://github.com/bounswe/2021SpringGroup9/blob/master/README.md) and [wiki home page](https://github.com/bounswe/2021SpringGroup9/wiki).
