### ISSUE TITLE
Examine Similar Software to our Project

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#28]
Find different projects that are related to our Project. Express common and different features. Share the information with the group via Wiki Page. 

After you complete the task please **check the box** next to your name:

- [x] Mert Alkan
- [x] Ahmet Melih Aydoğdu
- [x] Zehranaz Canfes
- [x] Mustafa Emir Çolak
- [x] Ömer Barış Erkek
- [x] Kadir Kalkan
- [x] Melih Özcan
- [x] Ahmet İbrahim Şentürk
- [x] Niyazi Ülke

**Comment by niyaziulke** [comment]
Everybody has completed the task.
