### ISSUE TITLE
Prepare a Question to be Clarified by our Customer

### ISSUE THREAD

**Issue by zcanfes** [bounswe/2021SpringGroup9#29]
Prepare **at least one** question to be asked to the customer. This question may be about the project's functionality, features, security etc. These questions will help us improve our project and add new features to it. 

After you complete the task please **check the box** next to your name:

- [x] Mert Alkan
- [x] Ahmet Melih Aydoğdu
- [x] Zehranaz Canfes
- [x] Mustafa Emir Çolak
- [x] Ömer Barış Erkek
- [x] Kadir Kalkan
- [x] Melih Özcan
- [x] Ahmet İbrahim Şentürk
- [x] Niyazi Ülke

**Comment by niyaziulke** [comment]
Created the [wiki page](https://github.com/bounswe/2021SpringGroup9/wiki/Questions-For-Customer) and wrote my question.

**Comment by zcanfes** [comment]
Everyone has prepared questions to ask to the customer. I am closing this issue.
