### ISSUE TITLE
Frontend API integration

### ISSUE THREAD

**Issue by mecolak** [bounswe/2021SpringGroup9#425]
### Task:
Integrate the backend API (newly deployed end-points) to the frontend.

### Type of task (new feature, writing tests, refactoring):
- [x] Discover Page
- [x] Create Post Page
- [ ] Like a Post

### Standards and rules to follow:
 Use API methods instead of mock data.
### Expected result:
The user should be able to sign up, sign in, create and edit posts and see posts on the discover pages and main pages.

### Additional notes:

**Deadline: 12.12.2021**

**Comment by ahmetsenturk** [comment]
We have added the discover page end-point. See 30e8695

**Comment by mecolak** [comment]
Create and edit post functionalities integrated as well. There are some minor issues with edit but it should be fixed in another branch. Issueing a pr.
