### ISSUE TITLE
Private User Basic Info Is Inaccessible at Profile Page

### ISSUE THREAD

**Issue by niyaziulke** [bounswe/2021SpringGroup9#556]
### Platform information(framework version, IDE version, browser etc.):

1. Backend

### Steps to reproduce the bug:

1. Search for a private user
2. Go to profile page of the private user

### Expected result:

The username, name, surname etc. (User class) of a private user is visible at the profile page of a private user but the posts are not visible.

### Actual result:

* The posts of the private user is invisible. (correct)
* But other information to identify the user is also invisible. The API returns 401 code from ``` api/user/get/<user_id>``` endpoint. The application crashes on both frontend and mobile platforms.

**Comment by zcanfes** [comment]
I fixed this problem. Now it works as expected. The related commit can be found [here](https://github.com/bounswe/2021SpringGroup9/commit/86de77473f094f074f2331917597fb75087347f3).

**Comment by zcanfes** [comment]
Another bug occured that caused the endpoint `api/post/all/user/<user_id> to return 401 if user_id is private and was followed by the logged in user.

**Comment by zcanfes** [comment]
I also fixed this bug. The related commit can be found [here](https://github.com/bounswe/2021SpringGroup9/commit/2b56f319bf175f3da4c0b28279851f411aa083b6).

**Comment by zcanfes** [comment]
I am closing this issue. Everything works fine.
